Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -40,19 +40,24 @@ jobs:
         run: |
           docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
 
-      - name: Install Trivy and Scan Image from ECR
+      - name: Install Trivy
         run: |
           curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
-          ./trivy image --skip-update -f json -o trivy-report.json $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG || echo "Trivy scan completed with vulnerabilities."
+
+      - name: Trivy Scan ECR Image
+        run: |
+          ./trivy image --timeout 5m --skip-update -f json -o trivy-report.json $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG || echo "Trivy scan completed with vulnerabilities or warnings."
 
       - name: Upload Trivy Report to S3
         run: |
           if [ -f trivy-report.json ]; then
+            echo "✅ Trivy report found, uploading..."
             aws s3 cp trivy-report.json s3://$S3_BUCKET/trivy-report-${IMAGE_TAG}.json
           else
-            echo "❌ trivy-report.json not found."
-            exit 1
+            echo "❌ trivy-report.json not found. Skipping upload."
+            # Optional: don't exit, continue with deploy
           fi
+
 
       - name: Deploy to ECS
         run: |
