Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -46,8 +46,8 @@ jobs:
 
       - name: Trivy Scan ECR Image
         run: |
-          echo "🛡 Scanning $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
-          ./trivy image --timeout 5m --skip-update -f json -o trivy-report.json $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG || echo "Trivy scan completed with vulnerabilities or warnings."
+         echo "🛡 Scanning $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
+         trivy image --timeout 5m --skip-update -f json -o trivy-report.json $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG || echo "Trivy scan completed with vulnerabilities or warnings."
 
       - name: Upload Trivy Report to S3
         if: success()
@@ -55,7 +55,7 @@ jobs:
           if [ -f trivy-report.json ]; then
             aws s3 cp trivy-report.json s3://$S3_BUCKET/trivy-report-${IMAGE_TAG}.json
           else
-            echo "❌ trivy-report.json not found. Skipping upload."
+            echo " trivy-report.json not found. Skipping upload."
           fi
 
       - name: Deploy to ECS
